# This is a basic workflow to help you get started with Actions

name: Freenom 域名自动续期

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
      - name: 检出主分支
        uses: actions/checkout@master
      - name: 创建PHP环境
        uses: franzliedke/gh-action-php@master
      - name: 写入配置文件
        run: |
          if [ '${{ secrets.FREENOM_USERNAME }}' != '' ]; then sed -i "s/^FREENOM_USERNAME=.*$/FREENOM_USERNAME='嘿嘿'/" fuck.env; else echo '保持默认值'; fi
          if [ '${{ secrets.FUCK }}' != '' ]; then sed -i "s/^FREENOM_USERNAME=.*$/FREENOM_USERNAME='嘿嘿'/" fuck.env; else echo '你没有设置 FUCK 值！'; fi
          cat fuck.env
      - name: 开始运行
        run: |
          php7.2 --version
